name: Check number proposals

on:
  push:
    branches: [ master ]
  schedule:
    # Every 20 minutes
    - cron: "*/20 * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    environment: updater

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - run: yarn
      - run: node src/index.js
        env:
          EXPECTED_PROPOSALS: ${{ secrets.EXPECTED_PROPOSALS }}
